name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
    - name: Checkout e2e-tests repo
      uses: actions/checkout@v3

    - name: Clone Producer Repo
      uses: actions/checkout@v3
      with:
        repository: ritesh-nethize/ProducerService
        path: Producer

    - name: Clone Consumer Repo
      uses: actions/checkout@v3
      with:
        repository: ritesh-nethize/ConsumerService
        path: Consumer

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Start dependencies
      run: docker-compose up -d

    - name: Build Producer & Consumer
      run: |
        dotnet build Producer/Producer.csproj --no-restore
        dotnet build Consumer/Consumer.csproj --no-restore

    - name: Run Producer
      run: dotnet run --project Producer/Producer.csproj &
   
    - name: Run Consumer
      run: dotnet run --project Consumer/Consumer.csproj &

    - name: Wait for services
      run: sleep 20

    - name: Run E2E Tests
      run: dotnet test E2ETests/E2ETests.csproj
